### ISSUE TITLE
Invalid FilterExpression

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/PocoDynamo#12]
`FromScan` method is throwing an exception, please see below description.

**Model**
```
    public class File
    {
        [PrimaryKey]
        public string Path { get; set; }
    }
```

**Call**
`dynamoDb_.FromScan<Types.File>(f => f.Path.StartsWith("d")).Exec().ToList();`

**Exception**
```
Amazon.DynamoDBv2.AmazonDynamoDBException : Invalid FilterExpression: An expression attribute name used in the document path is not defined; attribute name: #PA
  ----> Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at ServiceStack.TaskExt.GetResult(Task task)
   at ServiceStack.Aws.NetCoreAwsExtensions.Scan(IAmazonDynamoDB client, ScanRequest request)
   at ServiceStack.Aws.DynamoDb.PocoDynamo.Exec[T](Func`1 fn, Type[] rethrowExceptions, HashSet`1 retryOnErrorCodes)
   at ServiceStack.Aws.DynamoDb.PocoDynamo.<Scan>d__87`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
--HttpErrorResponseException
   at Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 443
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()

```

**Libraries**
1. AWSSDK.DynamoDBv2 v3.3.7.1
1. ServiceStack.Aws v5.0.2

**Comment by mythz** [comment]
The issue was due to `Path` being a reserved word which should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Aws/commit/05a4c4bf832409a95a894d29bb6fec5d4beef503).

This change is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).

Note: we're consolidating all our different project issues to use https://github.com/ServiceStack/Issues - please submit any future issues to there instead, thx.
